// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: grpc/proto/createUser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pessoa *Pessoa `protobuf:"bytes,1,opt,name=pessoa,proto3" json:"pessoa,omitempty"`
	Outros *Outros `protobuf:"bytes,2,opt,name=outros,proto3" json:"outros,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_createUser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_createUser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_proto_createUser_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPessoa() *Pessoa {
	if x != nil {
		return x.Pessoa
	}
	return nil
}

func (x *Request) GetOutros() *Outros {
	if x != nil {
		return x.Outros
	}
	return nil
}

type Pessoa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome             string `protobuf:"bytes,1,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Sobrenome        string `protobuf:"bytes,2,opt,name=Sobrenome,proto3" json:"Sobrenome,omitempty"`
	Idade            int32  `protobuf:"varint,3,opt,name=Idade,proto3" json:"Idade,omitempty"`
	DataDeNascimento string `protobuf:"bytes,4,opt,name=DataDeNascimento,proto3" json:"DataDeNascimento,omitempty"`
}

func (x *Pessoa) Reset() {
	*x = Pessoa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_createUser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pessoa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pessoa) ProtoMessage() {}

func (x *Pessoa) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_createUser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pessoa.ProtoReflect.Descriptor instead.
func (*Pessoa) Descriptor() ([]byte, []int) {
	return file_grpc_proto_createUser_proto_rawDescGZIP(), []int{1}
}

func (x *Pessoa) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Pessoa) GetSobrenome() string {
	if x != nil {
		return x.Sobrenome
	}
	return ""
}

func (x *Pessoa) GetIdade() int32 {
	if x != nil {
		return x.Idade
	}
	return 0
}

func (x *Pessoa) GetDataDeNascimento() string {
	if x != nil {
		return x.DataDeNascimento
	}
	return ""
}

type Outros struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodigosCertificados []string `protobuf:"bytes,1,rep,name=CodigosCertificados,proto3" json:"CodigosCertificados,omitempty"`
}

func (x *Outros) Reset() {
	*x = Outros{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_createUser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outros) ProtoMessage() {}

func (x *Outros) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_createUser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outros.ProtoReflect.Descriptor instead.
func (*Outros) Descriptor() ([]byte, []int) {
	return file_grpc_proto_createUser_proto_rawDescGZIP(), []int{2}
}

func (x *Outros) GetCodigosCertificados() []string {
	if x != nil {
		return x.CodigosCertificados
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pessoa *Pessoa `protobuf:"bytes,2,opt,name=pessoa,proto3" json:"pessoa,omitempty"`
	Outros *Outros `protobuf:"bytes,3,opt,name=outros,proto3" json:"outros,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_createUser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_createUser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpc_proto_createUser_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetPessoa() *Pessoa {
	if x != nil {
		return x.Pessoa
	}
	return nil
}

func (x *Response) GetOutros() *Outros {
	if x != nil {
		return x.Outros
	}
	return nil
}

var File_grpc_proto_createUser_proto protoreflect.FileDescriptor

var file_grpc_proto_createUser_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x70, 0x65, 0x73, 0x73,
	0x6f, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x65, 0x73, 0x73, 0x6f,
	0x61, 0x52, 0x06, 0x70, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x12, 0x1f, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x72, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4f, 0x75, 0x74, 0x72,
	0x6f, 0x73, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x72, 0x6f, 0x73, 0x22, 0x7c, 0x0a, 0x06, 0x50, 0x65,
	0x73, 0x73, 0x6f, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x62, 0x72,
	0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x6f, 0x62,
	0x72, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x64, 0x61, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x49, 0x64, 0x61, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x10,
	0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x4e, 0x61, 0x73, 0x63, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x4e, 0x61,
	0x73, 0x63, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x72,
	0x6f, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x73, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x13, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x73, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x64, 0x6f, 0x73, 0x22, 0x5c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x06, 0x70, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x50, 0x65, 0x73, 0x73, 0x6f, 0x61, 0x52, 0x06, 0x70, 0x65, 0x73, 0x73, 0x6f,
	0x61, 0x12, 0x1f, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x72, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x4f, 0x75, 0x74, 0x72, 0x6f, 0x73, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x72,
	0x6f, 0x73, 0x32, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x27, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_createUser_proto_rawDescOnce sync.Once
	file_grpc_proto_createUser_proto_rawDescData = file_grpc_proto_createUser_proto_rawDesc
)

func file_grpc_proto_createUser_proto_rawDescGZIP() []byte {
	file_grpc_proto_createUser_proto_rawDescOnce.Do(func() {
		file_grpc_proto_createUser_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_createUser_proto_rawDescData)
	})
	return file_grpc_proto_createUser_proto_rawDescData
}

var file_grpc_proto_createUser_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_proto_createUser_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: Request
	(*Pessoa)(nil),   // 1: Pessoa
	(*Outros)(nil),   // 2: Outros
	(*Response)(nil), // 3: Response
}
var file_grpc_proto_createUser_proto_depIdxs = []int32{
	1, // 0: Request.pessoa:type_name -> Pessoa
	2, // 1: Request.outros:type_name -> Outros
	1, // 2: Response.pessoa:type_name -> Pessoa
	2, // 3: Response.outros:type_name -> Outros
	0, // 4: CreateUser.RequestMessage:input_type -> Request
	3, // 5: CreateUser.RequestMessage:output_type -> Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_proto_createUser_proto_init() }
func file_grpc_proto_createUser_proto_init() {
	if File_grpc_proto_createUser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_createUser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_createUser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pessoa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_createUser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outros); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_createUser_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_createUser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_createUser_proto_goTypes,
		DependencyIndexes: file_grpc_proto_createUser_proto_depIdxs,
		MessageInfos:      file_grpc_proto_createUser_proto_msgTypes,
	}.Build()
	File_grpc_proto_createUser_proto = out.File
	file_grpc_proto_createUser_proto_rawDesc = nil
	file_grpc_proto_createUser_proto_goTypes = nil
	file_grpc_proto_createUser_proto_depIdxs = nil
}
